const yesNoOptions = [
  { value: "", label: "選択してください" },
  { value: "0", label: "0. なし" },
  { value: "1", label: "1. あり" },
];

// page14: コミュニケーション・認知関連のJSON定義。
const page14 = {
  id: 14,
  formTitle: "APOS-HC 調査票",
  badge: "No.14",
  fields: [
    {
      type: "group",
      key: "diseaseStatus",
      label: "主な疾患・障害の有無",
      fields: [
        {
          type: "group",
          key: "frailty",
          label: "高齢による衰弱",
          fields: [
            { type: "select", key: "frailty_exist", label: "有無", options: yesNoOptions },
            {
              type: "select",
              key: "frailty_detail_select",
              label: "詳細",
              visibleIf: { field: "frailty_exist", equals: "1" },
              options: [
                { value: "0", label: "詳細を選択" },
                { value: "1", label: "特に疾患がなく老いて体の機能が衰弱" },
                { value: "2", label: "便秘" },
                { value: "3", label: "食欲低下" },
                { value: "4", label: "フレイル" },
                { value: "99", label: "その他病名" },
              ],
            },
            {
              type: "text",
              key: "frailty_other",
              label: "その他病名・補足",
              visibleIf: { field: "frailty_detail_select", equals: "99" },
            },
          ],
        },
        {
          type: "group",
          key: "dementia",
          label: "認知症",
          fields: [
            { type: "select", key: "dementia_exist", label: "有無", options: yesNoOptions },
            {
              type: "select",
              key: "dementia_detail_select",
              label: "種類",
              visibleIf: { field: "dementia_exist", equals: "1" },
              options: [
                { value: "0", label: "種類を選択" },
                { value: "1", label: "アルツハイマー" },
                { value: "2", label: "血管型" },
                { value: "3", label: "レビー小体型" },
                { value: "4", label: "軽度認知障害" },
                { value: "99", label: "その他の病名" },
              ],
            },
            {
              type: "text",
              key: "dementia_other",
              label: "その他病名・補足",
              visibleIf: { field: "dementia_detail_select", equals: "99" },
            },
          ],
        },
        {
          type: "group",
          key: "cancer",
          label: "悪性新生物（がん）",
          fields: [
            { type: "select", key: "cancer_exist", label: "有無", options: yesNoOptions },
            {
              type: "select",
              key: "cancer_detail_select",
              label: "種類",
              visibleIf: { field: "cancer_exist", equals: "1" },
              options: [
                { value: "0", label: "種類を選択" },
                { value: "1", label: "大腸" },
                { value: "2", label: "胃" },
                { value: "3", label: "気管・気管支・肺" },
                { value: "4", label: "乳房" },
                { value: "5", label: "前立腺" },
                { value: "6", label: "子宮" },
                { value: "7", label: "肝" },
                { value: "99", label: "その他病名" },
              ],
            },
            {
              type: "text",
              key: "cancer_other",
              label: "その他病名・補足",
              visibleIf: { field: "cancer_detail_select", equals: "99" },
            },
          ],
        },
        {
          type: "group",
          key: "circulatory",
          label: "脳血管・循環器疾患",
          fields: [
            { type: "select", key: "circulatory_exist", label: "有無", options: yesNoOptions },
            {
              type: "text",
              key: "circulatory_freewrite_input",
              label: "詳細・補足",
              visibleIf: { field: "circulatory_exist", equals: "1" },
            },
          ],
        },
        {
          type: "group",
          key: "bone",
          label: "骨折・関節疾患・下肢関連",
          fields: [
            { type: "select", key: "bone_exist", label: "有無", options: yesNoOptions },
            {
              type: "select",
              key: "bone_detail_select",
              label: "詳細",
              visibleIf: { field: "bone_exist", equals: "1" },
              options: [
                { value: "0", label: "該当する疾患を選択してください" },
                { value: "1", label: "脊椎障害" },
                { value: "2", label: "関節リュウマチ" },
                { value: "3", label: "関節症・関節炎" },
                { value: "4", label: "腰痛・坐骨神経痛" },
                { value: "5", label: "骨折" },
                { value: "6", label: "足の巻き爪・爪肥厚・爪白癬等" },
                { value: "99", label: "その他病名" },
              ],
            },
            {
              type: "text",
              key: "bone_other",
              label: "その他病名・補足",
              visibleIf: { field: "bone_detail_select", equals: "99" },
            },
          ],
        },
        {
          type: "group",
          key: "otherDisease",
          label: "その他の疾患",
          fields: [
            { type: "select", key: "leg_circulation_exist", label: "有無", options: yesNoOptions },
            {
              type: "text",
              key: "leg_circulation_freewrite_input",
              label: "詳細・補足",
              visibleIf: { field: "leg_circulation_exist", equals: "1" },
            },
            {
              type: "text",
              key: "leg_circulation_other",
              label: "その他病名・補足",
              visibleIf: { field: "leg_circulation_exist", equals: "1" },
            },
          ],
        },
      ],
    },
    {
      type: "group",
      key: "doctorPlan",
      label: "主治医の診断名・治療方針・生活指導の状況",
      fields: [
        {
          type: "textarea",
          key: "doctor_diagnosis_note",
          label: "主治医の診断名・治療方針・生活指導（自由記述）",
          rows: 4,
        },
        {
          type: "table",
          key: "other_hospitals",
          label: "他診療所・病院の状況",
          columns: [
            { key: "other_hospital", label: "他診療所・病院", type: "text" },
            { key: "diagnosis", label: "診断名", type: "text" },
            { key: "treatment_content", label: "内容", type: "text" },
            { key: "remarks", label: "備考", type: "text" },
          ],
          defaultRows: [{}, {}, {}],
        },
      ],
    },
    {
      type: "group",
      key: "visitingBehavior",
      label: "受診行動",
      fields: [
        {
          type: "select",
          key: "yes_no_select",
          label: "定期的な診察・訪問診療を受け、必要時に受診できるか",
          options: [
            { value: "", label: "選択してください" },
            { value: "yes", label: "0. はい" },
            { value: "no", label: "1. いいえ" },
          ],
        },
        {
          type: "multi",
          key: "no_reason",
          label: "いいえの場合の理由（複数選択可）",
          visibleIf: { field: "yes_no_select", equals: "no" },
          options: [
            { value: "a", label: "a. 通院が必要だが、定期受診しないことがある" },
            { value: "b", label: "b. 1人で通院できない" },
            { value: "c", label: "c. 代理受診で処方を受けている" },
            { value: "d", label: "d. 不要と思い受診を拒否する" },
            { value: "e", label: "e. 複数医療機関に受診している" },
            { value: "f", label: "f. 在宅医療・訪問看護資源が不十分" },
          ],
        },
      ],
    },
    {
      type: "group",
      key: "medicalCare",
      label: "医療処置・ケア",
      fields: [
        { type: "select", key: "nutrition_exist", label: "栄養", options: yesNoOptions },
        {
          type: "multi",
          key: "nutrition_type",
          label: "栄養の種類",
          visibleIf: { field: "nutrition_exist", equals: "1" },
          options: [
            { value: "central_venous", label: "中心静脈栄養" },
            { value: "nasal", label: "経鼻経管栄養" },
            { value: "peg", label: "PEG（胃ろう・腸ろう）" },
          ],
        },
        { type: "select", key: "injection_exist", label: "注射", options: yesNoOptions },
        {
          type: "multi",
          key: "injection_type",
          label: "注射の種類",
          visibleIf: { field: "injection_exist", equals: "1" },
          options: [
            { value: "subcutaneous_infusion", label: "皮下輸液" },
            { value: "blood_transfusion", label: "輸血" },
            { value: "insulin_self_injection", label: "インシュリン・自己注射" },
            { value: "intravenous_injection", label: "静脈内注射" },
            { value: "drip_infusion", label: "点滴" },
            { value: "subcutaneous_im_non_insulin", label: "皮下筋肉注射（インシュリン外）" },
          ],
        },
        { type: "select", key: "catheter_exist", label: "カテーテル", options: yesNoOptions },
        {
          type: "multi",
          key: "catheter_type",
          label: "カテーテルの種類",
          visibleIf: { field: "catheter_exist", equals: "1" },
          options: [
            { value: "indwelling_bladder_catheter", label: "膀胱留置カテーテル" },
            { value: "condom_catheter", label: "コンドームカテーテル" },
            { value: "self_catheterization", label: "導尿・自己導尿" },
            { value: "renal_catheter", label: "腎盂カテーテル" },
            { value: "bladder_drainage", label: "膀胱ドレナージ" },
            { value: "liver_catheter", label: "肝胆・肝胆嚢ドレナージ" },
          ],
        },
        { type: "select", key: "tracheotomy_exist", label: "気管切開", options: yesNoOptions },
        {
          type: "multi",
          key: "tracheotomy_type",
          label: "気管切開の種類",
          visibleIf: { field: "tracheotomy_exist", equals: "1" },
          options: [
            { value: "suction", label: "気管切開部処置" },
            { value: "inhalation", label: "気管カニューレ" },
          ],
        },
        { type: "select", key: "respiration_exist", label: "呼吸", options: yesNoOptions },
        {
          type: "multi",
          key: "respiration_type",
          label: "呼吸の種類",
          visibleIf: { field: "respiration_exist", equals: "1" },
          options: [
            { value: "suction", label: "吸引" },
            { value: "inhalation", label: "吸入" },
            { value: "home_oxygen", label: "在宅酸素" },
            { value: "ventilator", label: "人工呼吸器" },
          ],
        },
        { type: "select", key: "dialysis_exist", label: "透析", options: yesNoOptions },
        {
          type: "multi",
          key: "dialysis_type",
          label: "透析の種類",
          visibleIf: { field: "dialysis_exist", equals: "1" },
          options: [
            { value: "capd_apd", label: "腹膜透析（CAPD/APD）" },
            { value: "hemodialysis", label: "血液透析" },
          ],
        },
        { type: "select", key: "stoma_exist", label: "ストーマ", options: yesNoOptions },
        {
          type: "multi",
          key: "stoma_type",
          label: "ストーマの種類",
          visibleIf: { field: "stoma_exist", equals: "1" },
          options: [
            { value: "artificial_anus", label: "人工肛門" },
            { value: "artificial_bladder", label: "人工膀胱" },
          ],
        },
        { type: "select", key: "wound_exist", label: "創傷処置", options: yesNoOptions },
        {
          type: "multi",
          key: "wound_type",
          label: "創傷処置の種類",
          visibleIf: { field: "wound_exist", equals: "1" },
          options: [
            { value: "pressure_ulcer", label: "褥瘡" },
            { value: "wound", label: "創傷" },
          ],
        },
        { type: "select", key: "pain_management_exist", label: "疼痛管理", options: yesNoOptions },
        {
          type: "multi",
          key: "pain_management",
          label: "疼痛管理の種類",
          visibleIf: { field: "pain_management_exist", equals: "1" },
          options: [
            { value: "subcutaneous_injection", label: "持続皮下注射" },
            { value: "epidural_injection", label: "硬膜外注射" },
            { value: "oral_medication", label: "服薬" },
            { value: "patch_or_mucosal", label: "貼付剤/口腔粘膜吸収剤" },
            { value: "narcotic_use", label: "麻薬" },
          ],
        },
        {
          type: "select",
          key: "narcotic_use",
          label: "麻薬使用の有無",
          visibleIf: { field: "pain_management_exist", equals: "1" },
          options: [
            { value: "", label: "選択" },
            { value: "yes", label: "有" },
            { value: "no", label: "無" },
          ],
        },
        { type: "select", key: "self_measurement_exist", label: "自己測定", options: yesNoOptions },
        {
          type: "multi",
          key: "self_measurement",
          label: "自己測定の種類",
          visibleIf: { field: "self_measurement_exist", equals: "1" },
          options: [
            { value: "blood_glucose", label: "血糖自己測定" },
            { value: "continuous_monitor", label: "持続モニター測定" },
          ],
        },
        { type: "select", key: "oral_care_exist", label: "口腔・う歯・歯肉", options: yesNoOptions },
        {
          type: "multi",
          key: "oral_visit",
          label: "口腔ケアの利用",
          visibleIf: { field: "oral_care_exist", equals: "1" },
          options: [
            { value: "clinic", label: "通院" },
            { value: "home_visit", label: "往診" },
            { value: "dental_hygienist_visit", label: "訪問歯科衛生" },
          ],
        },
        { type: "select", key: "drug_management_exist", label: "薬剤管理", options: yesNoOptions },
        {
          type: "multi",
          key: "drug_management",
          label: "薬剤管理の種類",
          visibleIf: { field: "drug_management_exist", equals: "1" },
          options: [
            { value: "oral_medication", label: "内服薬" },
            { value: "suppository", label: "座薬" },
            { value: "eye_drops", label: "点眼薬" },
            { value: "external_medicine", label: "外用薬" },
            { value: "injection", label: "注射・輸液・輸血・透析等" },
          ],
        },
        { type: "select", key: "rehab_equipment_exist", label: "リハビリ機器使用", options: yesNoOptions },
        {
          type: "textarea",
          key: "rehab_equipment_description",
          label: "リハビリ機器の内容",
          rows: 2,
          visibleIf: { field: "rehab_equipment_exist", equals: "1" },
        },
        { type: "select", key: "rehab_aids_exist", label: "リハビリ補助具", options: yesNoOptions },
        {
          type: "textarea",
          key: "rehab_aids_description",
          label: "リハビリ補助具の内容",
          rows: 2,
          visibleIf: { field: "rehab_aids_exist", equals: "1" },
        },
      ],
    },
  ],
};

export default page14;
