// page4: ADL/IADL 系の評価項目を扱うJSON定義。
const page4 = {
  id: 4,
  formTitle: "APOS-HC 調査票",
  badge: "No.4",
  fields: [
    {
      type: "group",
      key: "caregiverPresence",
      label: "介護者の有無",
      fields: [
        {
          type: "select",
          key: "hasCaregiver",
          label: "身近に家族介護者はいますか。",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "いない" },
            { value: "1", label: "いる" },
          ],
        },
      ],
    },
    {
      type: "group",
      key: "careBurden",
      label: "Ⅰ　介護負担の状況",
      visibleIf: { field: "hasCaregiver", equals: "1" },
      fields: [
        {
          type: "select",
          key: "feeling",
          label: "1) 心身への影響１",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 全く思わない" },
            { value: "1", label: "1 ごく軽く思う" },
            { value: "2", label: "2 軽く思う" },
            { value: "3", label: "3 かなり思う" },
            { value: "4", label: "4 非常に思う" },
          ],
        },
        {
          type: "select",
          key: "health",
          label: "2) 心身への影響２",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 全く思わない" },
            { value: "1", label: "1 ごく軽く思う" },
            { value: "2", label: "2 軽く思う" },
            { value: "3", label: "3 かなり思う" },
            { value: "4", label: "4 非常に思う" },
          ],
        },
        {
          type: "select",
          key: "life",
          label: "3) 生活への影響1",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 全く思わない" },
            { value: "1", label: "1 ごく軽く思う" },
            { value: "2", label: "2 軽く思う" },
            { value: "3", label: "3 かなり思う" },
            { value: "4", label: "4 非常に思う" },
          ],
        },
        {
          type: "select",
          key: "work",
          label: "4) 生活への影響2",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 全く思わない" },
            { value: "1", label: "1 ごく軽く思う" },
            { value: "2", label: "2 軽く思う" },
            { value: "3", label: "3 かなり思う" },
            { value: "4", label: "4 非常に思う" },
          ],
        },
        {
          type: "select",
          key: "impact",
          label: "5) 仕事・学業への影響",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 全く思わない" },
            { value: "1", label: "1 ごく軽く思う" },
            { value: "2", label: "2 軽く思う" },
            { value: "3", label: "3 かなり思う" },
            { value: "4", label: "4 非常に思う" },
          ],
        },
        {
          type: "group",
          key: "period",
          label: "介護の期間",
          fields: [
            { type: "text", key: "years", label: "どの位の期間介護を続けられていますか（年）", inputType: "number", min: 0, max: 99, placeholder: "例：3" },
            { type: "text", key: "months", label: "ヶ月", inputType: "number", min: 0, max: 11, placeholder: "例：6" },
          ],
        },
        {
          type: "select",
          key: "intention",
          label: "介護継続意向",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0. いろいろな制度や社会的サービスを使いながら常にこのままつづけたい" },
            { value: "1", label: "1. 制度やサービスを紹介してもらい継続したい" },
            { value: "2", label: "2. 様子を見ながら継続可否を判断したい" },
            { value: "3", label: "3. 兄弟・姉妹等への代替え予定" },
            { value: "4", label: "4. 施設を考えているが手続きは未実施" },
            { value: "5", label: "5. 在宅の継続は考えていない、施設入所を申請し順番を待っている" },
          ],
        },
      ],
    },
    {
      type: "group",
      key: "careReality",
      label: "Ⅱ　介護の実態",
      visibleIf: { field: "hasCaregiver", equals: "1" },
      fields: [
        {
          type: "select",
          key: "abuseInjury",
          label: "1. 創傷の発生（身体的虐待）",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 創傷や負傷はない" },
            { value: "1", label: "1 過去あったが1ヶ月間に創傷はない" },
            { value: "2", label: "2 既に治った創傷はあるが新たなものはない" },
            { value: "3", label: "3 様々な治癒段階の傷や骨折がある" },
            { value: "4", label: "4 多くの創傷や骨折がある" },
          ],
        },
        {
          type: "select",
          key: "neglectHygiene",
          label: "2. 身体の不衛生（ケアの放置）",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 不衛生による発疹や感染はない" },
            { value: "1", label: "1 過去あったが1ヶ月間に不衛生による発疹・感染はない" },
            { value: "2", label: "2 既に治った発疹・感染はあるが新たなものはない" },
            { value: "3", label: "3 不衛生による発疹・感染が様々にある" },
            { value: "4", label: "4 多くの不衛生による発疹・感染がある" },
          ],
        },
        {
          type: "select",
          key: "psychologicalAbuse",
          label: "3. 言葉による攻撃や否定的メッセージの持続（心理的虐待）",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 言葉の攻撃や否定的メッセージはない" },
            { value: "1", label: "1 過去あったが1か月間に言葉や否定的メッセージはない" },
            { value: "2", label: "2 過去あったが新たなものはない" },
            { value: "3", label: "3 時に言葉の攻撃または否定的メッセージを行う" },
            { value: "4", label: "4 数多く言葉の攻撃または否定的メッセージを行う" },
          ],
        },
        {
          type: "select",
          key: "neglectCare",
          label: "4. 介護等世話の放棄（ネグレクト）/拘束",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 介護放棄・拘束の状態は見当たらない" },
            { value: "1", label: "1 過去1ヶ月間に介護放棄・拘束の状態はない" },
            { value: "2", label: "2 過去にあったが新たにはない" },
            { value: "3", label: "3 時に介護を放棄・拘束している" },
            { value: "4", label: "4 殆ど介護されず放棄・拘束状態となっている" },
          ],
        },
        {
          type: "select",
          key: "sexualAbuse",
          label: "5. 性的暴力",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 性的暴力は全くない" },
            { value: "1", label: "1 過去1ヶ月間に性的暴力はない" },
            { value: "2", label: "2 過去にあったが新たなものはない" },
            { value: "3", label: "3 時に性的暴力を行っている" },
            { value: "4", label: "4 頻繁に性的暴力を行っている" },
          ],
        },
        {
          type: "select",
          key: "financialAbuse",
          label: "6. 金銭的な受け渡しの参加",
          options: [
            { value: "", label: "選択してください" },
            { value: "0", label: "0 本人の金銭は本人の意思に沿って使用している" },
            { value: "1", label: "1 過去1ヶ月間に金銭的トラブルはない" },
            { value: "2", label: "2 過去にトラブルがあったが新たなものはない" },
            { value: "3", label: "3 時に金銭的トラブル行為がある" },
            { value: "4", label: "4 頻繁に金銭的トラブル行為がある" },
          ],
        },
      ],
    },
  ],
};

export default page4;
